import "./globals.css";
import { Inter } from "next/font/google";

// import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/navbar";
import { cn, currentUser } from "@/lib/utils";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog App",
  description: "Generated by blog next app",
};

export default async function RootLayout({ children }) {
  const user = await currentUser();
  return (
    <html lang="en">
      <body
        className={cn("flex flex-col customized-scrollbar", inter.className)}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster Position="top-right" richColors duration={2500} />
          <Navbar user={user} />
          <main className="flex-grow">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
